customCommands:

    # TODO: when creating new branch add a counter to the name like feature-001/... feature-002

  - key: 'N'
    context: 'localBranches'
    prompts:
      - type: 'menu'
        title: 'What kind of branch is it?'
        key: 'BranchType'
        options:
          - name: 'feature'
            description: 'a feature branch'
            value: 'feature'
          - name: 'hotfix'
            description: 'a hotfix branch'
            value: 'hotfix'
          - name: 'release'
            description: 'a release branch'
            value: 'release'
          - name: 'bugfix'
            description: 'a bugfix branch'
            value: 'bugfix'
      - type: 'input'
        title: 'What is the new branch name?'
        key: 'BranchName'
        initialValue: ''
    command: |
      BRANCH_TYPE="{{.Form.BranchType}}"
      BRANCH_NAME="{{.Form.BranchName}}"
      
      # Get the highest existing branch number
      LAST_BRANCH=$(git branch --list "$BRANCH_TYPE-[0-9][0-9][0-9]/*" | grep -o "$BRANCH_TYPE-[0-9][0-9][0-9]" | sed 's/[^0-9]*//g' | sort -nr | head -n1)
      
      # Increment the number for the new branch
      if [ -z "$LAST_BRANCH" ]; then
        NEW_BRANCH_NUMBER="001"
      else
        NEW_BRANCH_NUMBER=$(printf "%03d" $((LAST_BRANCH + 1)))
      fi
      
      # Create the new branch with the incremented number
      git checkout -b "$BRANCH_TYPE-$NEW_BRANCH_NUMBER/$BRANCH_NAME"
    loadingText: 'Creating branch'

  - key: 'C'
    context: 'localBranches'
    command: |
      CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
      git push --set-upstream origin $CURRENT_BRANCH
    loadingText: 'Pushing Current Branch'
    

  - key: 'D'
    context: 'localBranches'
    prompts:
      - type: 'menu'
        title: 'Select local branch to merge to after pushing to origin'
        key: 'TargetBranch'
        options:  
          - name: 'dev'
            description: 'dev'
            value: 'dev'
          - name: 'main'
            description: 'main'
            value: 'main'
    command: |
      CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
      git push --set-upstream origin $CURRENT_BRANCH
      git checkout {{.Form.TargetBranch}}
      git merge $CURRENT_BRANCH
      git branch -d $CURRENT_BRANCH
    loadingText: 'Pushing and merging branch'
    
