customCommands:
  - key: 'N'
    context: 'localBranches'
    prompts:
      - type: 'menu'
        title: 'What kind of branch is it?'
        key: 'BranchType'
        options:
          - name: 'feature'
            description: 'a feature branch'
            value: 'feature'
          - name: 'hotfix'
            description: 'a hotfix branch'
            value: 'hotfix'
          - name: 'release'
            description: 'a release branch'
            value: 'release'
          - name: 'bugfix'
            description: 'a bugfix branch'
            value: 'bugfix'
      - type: 'input'
        title: 'What is the new branch name?'
        key: 'BranchName'
        initialValue: ''
    command: "git checkout -b {{.Form.BranchType}}/{{.Form.BranchName}}"
    loadingText: 'Creating branch'


  - key: 'C'
    context: 'localBranches'
    command: |
      CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
      git push --set-upstream origin $CURRENT_BRANCH
    loadingText: 'Pushing Current Branch'
    

  - key: 'D'
    context: 'localBranches'
    prompts:
      - type: 'menu'
        title: 'Select local branch to merge to after pushing to origin'
        key: 'TargetBranch'
        options:  
          - name: 'dev'
            description: 'dev'
            value: 'dev'
          - name: 'main'
            description: 'main'
            value: 'main'
    command: |
      CURRENT_BRANCH=$(git rev-parse --abbrev-ref HEAD)
      git push --set-upstream origin $CURRENT_BRANCH
      git checkout {{.Form.TargetBranch}}
      git merge $CURRENT_BRANCH
      git branch -d $CURRENT_BRANCH
    loadingText: 'Pushing and merging branch'
    
